// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG0Nxmy4igVCAucT9Ww4i51j9cXwiDfXI',
    appId: '1:1017582424994:web:5bfac1e5548bba5aea98fb',
    messagingSenderId: '1017582424994',
    projectId: 'tritrack-713a1',
    authDomain: 'tritrack-713a1.firebaseapp.com',
    databaseURL: 'https://tritrack-713a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tritrack-713a1.firebasestorage.app',
    measurementId: 'G-692Q261Z7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoopqvYo4vw2ob-tKbCUshK8UK0Hqh9_c',
    appId: '1:1017582424994:android:e44edf6d3c75abc5ea98fb',
    messagingSenderId: '1017582424994',
    projectId: 'tritrack-713a1',
    databaseURL: 'https://tritrack-713a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tritrack-713a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrolDS-d4pgz0aGEE_RohSg3ozxqGoKTY',
    appId: '1:1017582424994:ios:461c7cbf669381ceea98fb',
    messagingSenderId: '1017582424994',
    projectId: 'tritrack-713a1',
    databaseURL: 'https://tritrack-713a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tritrack-713a1.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrolDS-d4pgz0aGEE_RohSg3ozxqGoKTY',
    appId: '1:1017582424994:ios:461c7cbf669381ceea98fb',
    messagingSenderId: '1017582424994',
    projectId: 'tritrack-713a1',
    databaseURL: 'https://tritrack-713a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tritrack-713a1.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG0Nxmy4igVCAucT9Ww4i51j9cXwiDfXI',
    appId: '1:1017582424994:web:a957fe03d267bfc8ea98fb',
    messagingSenderId: '1017582424994',
    projectId: 'tritrack-713a1',
    authDomain: 'tritrack-713a1.firebaseapp.com',
    databaseURL: 'https://tritrack-713a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tritrack-713a1.firebasestorage.app',
    measurementId: 'G-FDV3M7DHB5',
  );
}
